name: test
'on':
  push:
    branches:
      - main
jobs:
  test:
    name: sonarQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: uses Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: install dependencies
        working-directory: ./client
        run: npm ci
      - run: CI='' npm run build
        working-directory: ./client
      - run: npm run test
        working-directory: ./client
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_FART }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID=: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_MEASURMENT_ID: ${{ secrets.REACT_APP_MEASURMENT_ID }}
      - uses: actions/checkout@master
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_FART }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID=: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_MEASURMENT_ID: ${{ secrets.REACT_APP_MEASURMENT_ID }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_FART }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID=: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_MEASURMENT_ID: ${{ secrets.REACT_APP_MEASURMENT_ID }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
