name: test
'on':
  push:
    branches:
      - main
jobs:
  test:
    name: sonarQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ci and test
        working-directory: ./client
        run: sudo npm ci && npm run test #&& sonar-scanner
      - uses: actions/checkout@master
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: Run sonarqube
        run: sonar-scanner
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #- name: SonarQube Scan
      #  uses: sonarsource/sonarqube-scan-action@master
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #- uses: actions/checkout@v2
      # with:
      #  fetch-depth: 0